class RSMConfig:
    """Configuration constants for RSM model operations"""
    TEAM_NAME = "AUDAUTO"
    MODEL_NAME = "RSM"
    PREV_EMBEDDING_TRACK_COUNT = 4
    POLICY_TABLE_PATH_TAG_NAME = "POLICY_TABLE_PATH"
    BID_REQUEST_MODEL_PATH_TAG_NAME = "BID_REQUEST_MODEL_PATH"
    SEED_EMBEDDING_PATH_TAG_NAME = "SEED_EMBEDDING_PATH"
    PREV_SEED_EMBEDDING_PATHS_TAG_NAME = "PREV_SEED_EMBEDDING_PATHS"
    MODEL_MAPPING_LOG_BUCKET = "thetradedesk-mlplatform-us-east-1"
    MODEL_MAPPING_LOG_PATH = "configdata/prod/audience/embedding/RSMV2/v=1/_MAPPING"
