apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
  annotations:
    gitlab/ref: {{ .Values.ref }}
    gitlab/user-login: {{ .Values.user_login }}
    gitlab/mr-url: {{ .Values.mr_url }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Gi
  storageClassName: standard-ssd-encrypted
