apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    component: db
  name: {{ .Values.name }}-db
  annotations:
    gitlab/ref: {{ .Values.ref }}
    gitlab/user-login: {{ .Values.user_login }}
    gitlab/mr-url: {{ .Values.mr_url }}
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: {{ .Values.name }}
    component: db