apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.name }}"
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - create
      - delete
      - list
      - get
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - get
